### ISSUE TITLE
Why is the normal Terminal not used when launching ssh shell on Linux?

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#151] opened 2016-11-20 12:06 UTC
I noticed we're using a very lousy vanilla xterm terminal instead of the standard terminal that comes on Ubuntu. It's a bit inconvenient.

**Comment by Lezh1k** [comment] 2016-11-21 03:08
Duplicate of https://github.com/subutai-io/tray/issues/135 . 
Close.

**Closed by Lezh1k** 2016-11-21 03:08 UTC
Labels: bug
