### ISSUE TITLE
Update Tray Debian package

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/tray#232] opened 2017-09-09 13:51 UTC
We need this for non Launcher based installations for people to be able to setup clients. In fact we need a Windows MSI and a Mac PKG for tray itself.

**Comment by Lezh1k** [comment] 2017-09-13 03:05
Done. Duplicate of https://github.com/subutai-io/tray/issues/231

**Closed** 2017-11-07 10:57 UTC
Labels: blocker, testing
